"""add Trainingsinhalt class in db

Revision ID: 0594c71c272b
Revises: 3ad756170ebd
Create Date: 2024-02-09 11:12:21.060755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0594c71c272b'
down_revision = '3ad756170ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_inhalt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uebungsname', sa.String(length=128), nullable=False),
    sa.Column('gewicht', sa.Float(), nullable=False),
    sa.Column('saetze', sa.Integer(), nullable=False),
    sa.Column('wiederholungen', sa.Integer(), nullable=False),
    sa.Column('training_day_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_inhalt')
    # ### end Alembic commands ###
