"""Added exercise_name to WorkoutDay

Revision ID: 91185660cd7c
Revises: f5524139c376
Create Date: 2024-02-08 19:45:59.081940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91185660cd7c'
down_revision = 'f5524139c376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_day', schema=None) as batch_op:
        batch_op.drop_column('exercise_name')

    # ### end Alembic commands ###
