"""delete db in db.py

Revision ID: 9893388a351c
Revises: 91185660cd7c
Create Date: 2024-02-09 05:07:12.753727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9893388a351c'
down_revision = '91185660cd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_day')
    op.drop_table('workout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_day_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sets', sa.INTEGER(), nullable=False),
    sa.Column('repetitions', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['workout_day_id'], ['workout_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_day',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('day_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
