"""Added gewicht and zielgewicht to User

Revision ID: cd9bea1cbca2
Revises: 
Create Date: 2024-02-08 00:30:11.564646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9bea1cbca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_entry')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gewicht', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('zielgewicht', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zielgewicht')
        batch_op.drop_column('gewicht')

    op.create_table('dashboard_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('workout_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('slept_well', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
